project:
  type: book

book:
  title: "YALE BIS629_01"
  author: "Randy Jin"
  date: "9/8/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - 01_week1.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

